spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agora_dev
    username: agora
    password: agora
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enabled: true