Server=IP_DU_SERVEUR_PROF
ServerActive=IP_DU_SERVEUR_PROF
Hostname=agora-app

# ======================
# CHECK API
# ======================
UserParameter=api.health,curl -s http://backend:8080/actuator/health | grep '"status":"UP"'

# ======================
# CHECK DB
# ======================
UserParameter=db.ping,pg_isready -h postgres -p 5432

# ======================
# CHECK HTTP STATUS
# ======================
UserParameter=api.status,curl -o /dev/null -s -w "%{http_code}" http://backend:8080/actuator/health